ARG NODE_VERSION=20.14.0
FROM node:${NODE_VERSION}-slim as base
RUN apt-get update && apt-get install -y openssl
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG SESSION_NAME
ARG PORT
ARG DEFAULT_API_PREFIX
ARG JWT_SEED
ARG DATABASE_URL
ARG ENCRYPT_SALT
ARG DOMAIN

ENV NODE_ENV=production
ENV SESSION_NAME=$SESSION_NAME
ENV PORT=$PORT
ENV DEFAULT_API_PREFIX=$DEFAULT_API_PREFIX
ENV JWT_SEED=$JWT_SEED
ENV DATABASE_URL=$DATABASE_URL
ENV ENCRYPT_SALT=$ENCRYPT_SALT
ENV DOMAIN=$DOMAIN
RUN npm run prisma:generate
RUN npm run prisma:seed
RUN npm run build
CMD ["npm", "run", "start"]
